### ISSUE TITLE
ffmpeg 7.1 project file generate incompleted

### ISSUE THREAD

**Issue by kpld** [ShiftMediaProject/FFVS-Project-Generator#70]
ffmpeg 7.1 project file generate incompleted, and program quit.

**Comment by kpld** [comment]
Another compile error exist:
error C2011: 'DBParams': 'struct' type redefinition (compiling source file ../ffmpeg-7.1/libavcodec/hevc/hevcdec.c)
error C2011: 'RefPicList': 'struct' type redefinition (compiling source file ../ffmpeg-7.1/libavcodec/hevc/hevcdec.c)
error C2011: 'RefPicListTab': 'struct' type redefinition (compiling source file ../ffmpeg-7.1/libavcodec/hevc/hevcdec.c)

**Comment by kpld** [comment]
temporary add following lines in file [projectGenerator_compiler.cpp:95] to avoid struct type redefinition:
```
        if (extraCl.find("libavcodec/hevc") != string::npos && i.find("libavcodec/vvc") != string::npos) {
            continue;    
        }
        if (extraCl.find("libavcodec/vvc") != string::npos && i.find("libavcodec/hevc") != string::npos) {
            continue;
        }
        extraCl += " /I\"" + i + '\"';
```

**Comment by kpld** [comment]
end of function ProjectGenerator::outputSourceFiles, filterKeys item count is less than foundFilters item count, so need to add some filter key constant. Or it will be crashed.

**Comment by Sibras** [comment]
> has not check the return value in file [projectGenerator_pass.cpp:168] startPos = m_inLine.find_first_not_of(".\/", startPos); need to add following code: if (startPos == string::npos) return true;

Fixed in latest version of FFVS

> Another compile error exist: error C2011: 'DBParams': 'struct' type redefinition (compiling source file ../ffmpeg-7.1/libavcodec/hevc/hevcdec.c) error C2011: 'RefPicList': 'struct' type redefinition (compiling source file ../ffmpeg-7.1/libavcodec/hevc/hevcdec.c) error C2011: 'RefPicListTab': 'struct' type redefinition (compiling source file ../ffmpeg-7.1/libavcodec/hevc/hevcdec.c)

This is actually an error due to an incorrect checkout of FFmpeg when upgrading to 7.1. A forced/clean checkout to latest version fixes this.

> end of function ProjectGenerator::outputSourceFiles, filterKeys item count is less than foundFilters item count, so need to add some filter key constant. Or it will be crashed.

Fixed in latest version of FFVS

The latest FFVS has been updated and tested on ffmpeg 7.1 and should function correctly
